Update .travis.yml
freezing coveralls at version 1.1, since later version uses cryptography 1.9, which is not compatible with the default Travis pypy version.

    RuntimeError: cryptography 1.9 is not compatible with PyPy < 5.3. Please upgrade PyPy to use this library.